name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Download Source via API
        shell: powershell
        run: |
          $url = "https://github.com/${{ github.repository }}/archive/${{ github.ref_name }}.zip"
          Invoke-WebRequest -Uri $url -OutFile "source.zip"
          Expand-Archive -Path "source.zip" -DestinationPath "temp_extract"
          
          # Move files out of the nested folder that GitHub creates inside the zip
          $nestedFolder = Get-ChildItem -Path "temp_extract" | Select-Object -First 1
          Move-Item -Path "$($nestedFolder.FullName)\*" -Destination "." -Force
          
          # Clean up temporary archives
          Remove-Item -Path "source.zip" -Force
          Remove-Item -Path "temp_extract" -Recurse -Force


      - name: Setup Node 24 Environment
        run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/main.py
          mode: onefile
          enable-plugins: tk-inter
          include-data-files: src/icon.ico=src/icon.ico
          disable-console: true

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}